language: ruby
sudo: false
cache: bundler
bundler_args: '--path vendor/bundle'
gemfile:
  - gemfiles/32.gemfile
  - gemfiles/40.gemfile
  - gemfiles/41.gemfile
  - gemfiles/42.gemfile
  - gemfiles/50.gemfile
rvm:
  - 2.1.10
  - 2.2.5
script: bundle exec rake spec
# Rails is not supported on Ruby 2.1.x
matrix:
  exclude:
    - rvm: 2.1.10
      gemfile: gemfiles/50.gemfile